name: PHWestman
favicon: null
layout_spectrum: 0.13537700497545302
typography_spectrum: 0.07543987012468278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21059181238524616
  lightness: 0.8962239020038396
  saturation: 0.7191180342342705
  rhythmicContrast: 0.9118348469492048
purpose: []
